// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.CommandBase;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import frc.robot.RobotContainer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.MagicArm;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

public class MoveArmSimple extends CommandBase {

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
  private final MagicArm m_magicArm;

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

  // These are the extra variables required to run the MoveArmSimple command
  private double targetX;
  private double targetY;
  private boolean joyStickMoved = false;
  private double deltaScale = 175.0;

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
  /**
   * Default command for arm control
   * 
   * @param subsystem arm
   */
  public MoveArmSimple(MagicArm subsystem) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    m_magicArm = subsystem;
    addRequirements(m_magicArm);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
  }

  // Called when the command is initially scheduled.
  @Override
  public void initialize() {
    targetX = m_magicArm.getX();
    targetY = m_magicArm.getY();
    joyStickMoved = false;
  }

  // Called every time the scheduler runs while the command is scheduled.
  @Override
  public void execute() {
    // We are running out of buttons for half speed control. So push joysticks
    // towards each other is
    // half speed, pull them apart is full speed
    double axDifference = RobotContainer.getInstance().getArmController().getRawAxis(0);
    axDifference -= RobotContainer.getInstance().getArmController().getRawAxis(2);
    if (axDifference > 1.8) {
      deltaScale = 250;
    } else if (axDifference < -1.8) {
      deltaScale = 175;
    }
    double xSpeed = RobotContainer.getInstance().getArmController().getRawAxis(1) / deltaScale;
    double ySpeed = -RobotContainer.getInstance().getArmController().getRawAxis(3) / deltaScale;
    if (Math.abs(xSpeed) < (0.1 / deltaScale)) { // deadband
      xSpeed = 0;
    } else {
      joyStickMoved = true;
    }
    if (Math.abs(ySpeed) < (0.1 / deltaScale)) { // deadband
      ySpeed = 0;
    } else {
      joyStickMoved = true;
    }
    // First time joysticks not moved, get current arm tip position and keep it
    // there.
    if (Math.abs(xSpeed) < (0.1 / deltaScale) && Math.abs(ySpeed) < (0.1 / deltaScale) && joyStickMoved) {
      targetX = m_magicArm.getX();
      targetY = m_magicArm.getY();
      joyStickMoved = false;
    }
    // Get X and Y that is either at the target or at the robot/game limit.
    targetX = m_magicArm.getLimitX(targetX + xSpeed);
    targetY = m_magicArm.getLimitY(targetX, targetY + ySpeed);

    m_magicArm.moveTowardXY(targetX, targetY);

    SmartDashboard.putNumber("targetX", targetX / 0.0254);
    SmartDashboard.putNumber("targetY", targetY / 0.0254 + 11);
  }

  // Called once the command ends or is interrupted.
  @Override
  public void end(boolean interrupted) {
  }

  // Returns true when the command should end.
  @Override
  public boolean isFinished() {
    return false;
  }

  @Override
  public boolean runsWhenDisabled() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
  }
}
